apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: api 
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: init-pod
          image: busybox:1.28
          command: ["sh", "-c", "until nslookup mongodb-service.default.svc.cluster.local; do echo Aguardando o Banco de Dados; sleep 2; done"]    
      containers:
        - name: api 
          image: gmaas2/pedelogo-catalogo:1.0
          resources:
            requests:
              memory: 32Mi
              cpu: 100m
            limits:
              memory: 64Mi
              cpu: 500m          
          ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /read
              port: 80
              scheme: HTTP
            timeoutSeconds: 2
            failureThreshold: 3
            periodSeconds: 5
            successThreshold: 0
          livenessProbe:
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 80
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: api-configmap
          env:
            - name: Mongo__User
              valueFrom: 
                configMapKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: mongodb-configmap
            - name: Mongo__Password
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: mongodb-configmap
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app 
                      operator: In 
                      values: 
                        - "mongodb"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 2
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app 
                      operator: In 
                      values: 
                        - "api"                            
      #imagePullSecrets:
      #  - name: acr-gmaas
      #nodeSelector:
      #  app: api