apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  selector:
    matchLabels:
      type: local
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi