apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: api-deployment
spec:
  selector: 
    matchLabels:
      app: api 
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api 
          image: gmaas2/pedelogo-catalogo:1.0
          ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
          imagePullPolicy: Always
          env:
            - name: Mongo__Host
              value: "mongodb-service"
            - name: Mongo__User
              value: "mongouser"
            - name: Mongo__Password
              value: "mongopassword"
            - name: Mongo__Port
              value: "27017"
            - name: Mongo_Database
              value: "admin"
