NAME: api-teste
LAST DEPLOYED: Thu Nov 24 16:09:09 2022
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
api:
  serviceType: ClusterIP

COMPUTED VALUES:
api:
  image: gmaas2/pedelogo-catalogo:1.0
  serviceType: ClusterIP
mongodb:
  credentials:
    userName: mongouser
    userPassword: mongopwd
  databaseName: admin
  tag: 4.2.8

HOOKS:
MANIFEST:
---
# Source: api-produto/templates/api-service.yml
apiVersion: v1 
kind: Service 
metadata:
  name: api-teste-api-service
spec:
  selector:
    app: api-teste-api 
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
# Source: api-produto/templates/mongodb-service.yml
apiVersion: v1
kind: Service 
metadata:
  name: api-teste-mongodb-service
spec:
  selector:
    app: api-teste-mongodb
  ports:
    - port: 27017
      targetPort: 27017
---
# Source: api-produto/templates/api-deployment.yml
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: api-teste-api-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: api-teste-api 
  template:
    metadata:
      labels:
        app: api-teste-api
    spec: 
      containers:
        - name: api 
          image: gmaas2/pedelogo-catalogo:1.0
          ports:
          - containerPort: 80
          imagePullPolicy: Always        
          resources:
            requests:
              memory: 32Mi
              cpu: 100m
            limits:
              memory: 64Mi
              cpu: 500m          
          env:
            - name: Mongo__User
              value: mongouser
            - name: Mongo__Password
              value: mongopwd
            - name: Mongo__Host
              value: api-teste-mongodb-service
            - name: Mongo__Database
              value: admin
---
# Source: api-produto/templates/mongodb-deployment.yml
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: api-teste-mongodb-deployment
spec:
  selector:
    matchLabels:
      app: api-teste-mongodb
  template:
    metadata:
      labels:
        app: api-teste-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.2.8
          ports:
            - containerPort: 27017          
          resources:
            requests:
              memory: 256Mi
              cpu: 1000m
            limits:
              memory: 256Mi
              cpu: 1000m
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongouser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopwd

NOTES:
Instalando.
